# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, choices=[('Guru Teg Bahadur Rice Mill , Mahasamund', 'Guru Teg Bahadur Rice Mill , Mahasamund'), ('Pankaj Agrawal , Sinapali', 'Pankaj Agrawal , Sinapali'), ('Sunil Kumar Agrawal , Sohela', 'Sunil Kumar Agrawal , Sohela'), ('Rajendra Pali , Durg', 'Rajendra Pali , Durg')], max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('payment_type', models.CharField(blank=True, choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=100, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
