# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_data',
            new_name='payment_data',
        ),
    ]
