# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170102_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_data',
            name='firm_name',
            field=models.CharField(blank=True, choices=[('Guru Teg Bahadur Rice Mill , Mahasamund', 'Guru Teg Bahadur Rice Mill , Mahasamund'), ('Pankaj Agrawal , Sinapali', 'Pankaj Agrawal , Sinapali'), ('Sunil Kumar Agrawal , Sohela', 'Sunil Kumar Agrawal , Sohela'), ('Rajendra Pali , Durg', 'Rajendra Pali , Durg'), ('Radhe Rahe Traders , Varud', 'Radhe Rahe Traders , Varud')], max_length=255, null=True),
        ),
    ]
