# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20170102_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_data',
            name='payment_medium',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_data',
            name='remarks',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
