# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170102_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='order_type',
            field=models.CharField(blank=True, choices=[('PURCHASE', 'PURCHASE'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
