# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170102_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='firm_name',
            field=models.CharField(blank=True, choices=[('Guru Teg Bahadur Rice Mill , Mahasamund', 'Guru Teg Bahadur Rice Mill , Mahasamund'), ('Garu Teg Bahadur Rice Mill , Mahasamund', 'Garu Teg Bahadur Rice Mill , Mahasamund'), ('Pankaj Agrawal , Sinapali', 'Pankaj Agrawal , Sinapali'), ('Sunil Kumar Agrawal , Sohela', 'Sunil Kumar Agrawal , Sohela')], max_length=255, null=True),
        ),
    ]
