# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_data_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
