# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20170103_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='firm_name',
            field=models.CharField(blank=True, choices=[('Guru Teg Bahadur Rice Mill , Mahasamund', 'Guru Teg Bahadur Rice Mill , Mahasamund'), ('Pankaj Agrawal , Sinapali', 'Pankaj Agrawal , Sinapali'), ('Sunil Kumar Agrawal , Sohela', 'Sunil Kumar Agrawal , Sohela'), ('Rajendra Pali , Durg', 'Rajendra Pali , Durg'), ('Radhe Rahe Traders , Varud', 'Radhe Rahe Traders , Varud'), ('Kissan Rice Mill , Arang', 'Kissan Rice Mill , Arang'), ('Jay Shankar Rice Mill , Raipur', 'Jay Shankar Rice Mill , Raipur'), ('Jindal Rice Mill , Bagbara', 'Jindal Rice Mill , Bagbara'), ('Vishva Bharti Rice Mill , Raipur', 'Vishva Bharti Rice Mill , Raipur'), ('Konark Industries , Raipur', 'Konark Industries , Raipur'), ('Ratiram Tarachand , Raipur', 'Ratiram Tarachand , Raipur'), ('Balaji Rice Mill , Kharora', 'Balaji Rice Mill , Kharora'), ('Anil Rice Mill , Bilaspur', 'Anil Rice Mill , Bilaspur'), ('Vijay and Company , Rajim', 'Vijay and Company , Rajim'), ('Durga Trading , Raipur', 'Durga Trading , Raipur'), ('Sonia Cattlefeed , Raipur', 'Sonia Cattlefeed , Raipur'), ('Shri Nath Agro , Durg', 'Shri Nath Agro , Durg'), ('Mahendra Dalal , Raipur', 'Mahendra Dalal , Raipur'), ('Santosh Kumar Dewangan , Rajnandgaon', 'Santosh Kumar Dewangan , Rajnandgaon')], max_length=255, null=True),
        ),
    ]
